{% set name = "deepchem" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepchem/deepchem/archive/{{ version }}.tar.gz
  sha256: 6eb66aa0f7e66fd6f38bf6d5682e67f6d04d4ce2a800982e5c0156de5a6302eb

build:
  noarch: python
  number: 0
  script: PBR_VERSION=${PKG_VERSION} && export PBR_VERSION && {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.7,<3.10
    - pip
    - setuptools
    - pbr

  run:
    - python >=3.7,<3.10
    - joblib
    - numpy
    - pandas
    - scikit-learn
    - scipy

test:
  requires:
    - rdkit
  imports:
    - deepchem
  commands:
    - python run_test.py

about:
  home: https://github.com/deepchem/deepchem
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Democratizing Deep-Learning for Drug Discovery, Quantum Chemistry, Materials Science and Biology

extra:
  recipe-maintainers:
    - rbharath
    - simonbray
