{% set name = "deepchem" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepchem/deepchem/archive/{{ version }}.tar.gz
  sha256: 25ebc59a53c8dcd841dbebab00bbef85efe8c29fa33e49c36b751cbd2f76110c

build:
  noarch: python
  number: 0
  script: PBR_VERSION=${PKG_VERSION} && export PBR_VERSION && {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.5,<3.8
    - pip ==20.2.*
    - setuptools
    - pbr

  run:
    - python >=3.5,<3.8
    - pip ==20.2.*
    - joblib
    - numpy
    - pandas
    - scikit-learn
    - scipy

test:
  requires:
    - tensorflow>=2.3,<2.4
    - rdkit
  imports:
    - deepchem
  commands:
    - python run_test.py

about:
  home: https://github.com/deepchem/deepchem
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Democratizing Deep-Learning for Drug Discovery, Quantum Chemistry, Materials Science and Biology

extra:
  recipe-maintainers:
    - rbharath
    - simonbray
